const canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d');
const file=document.querySelector('#file'),zoom=document.querySelector('#zoom'),download=document.querySelector('#download'),empty=document.querySelector('#empty'),controls=document.querySelector('#controls'),grid=document.querySelector('#frameGrid');
const frames=[['Blue','frames/icon-frame-blue.png'],['Green','frames/icon-frame-green.png'],['Pink','frames/icon-frame-pink.png'],['Red','frames/icon-frame-red.png'],['White','frames/icon-frame-white.png']];
let user=null,frame=null,framePath=frames[0][1],scale=1,baseScale=1,x=0,y=0,drag=false,lastX=0,lastY=0;
function loadFrame(path){const im=new Image();im.onload=()=>{frame=im;draw()};im.src=path}loadFrame(framePath);
frames.forEach(([name,path],i)=>{const b=document.createElement('button');b.className='frame-btn'+(i===0?' active':'');b.type='button';b.setAttribute('aria-label',name+'のフレーム');b.innerHTML=`<img src="${path}" alt="${name}">`;b.onclick=()=>{document.querySelectorAll('.frame-btn').forEach(v=>v.classList.remove('active'));b.classList.add('active');framePath=path;loadFrame(path)};grid.appendChild(b)});
function resetPosition(){if(!user)return;baseScale=Math.max(canvas.width/user.width,canvas.height/user.height);scale=1;x=(canvas.width-user.width*baseScale)/2;y=(canvas.height-user.height*baseScale)/2;zoom.value=1;draw()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);if(user){const s=baseScale*scale;ctx.drawImage(user,x,y,user.width*s,user.height*s)}if(frame)ctx.drawImage(frame,0,0,canvas.width,canvas.height)}
file.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f),im=new Image();im.onload=()=>{user=im;URL.revokeObjectURL(url);empty.hidden=true;controls.hidden=false;download.disabled=false;resetPosition()};im.src=url};
zoom.oninput=()=>{if(!user)return;const old=scale;scale=+zoom.value;const cx=canvas.width/2,cy=canvas.height/2;x=cx-(cx-x)*(scale/old);y=cy-(cy-y)*(scale/old);draw()};document.querySelector('#reset').onclick=resetPosition;
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{if(!user)return;drag=true;canvas.setPointerCapture(e.pointerId);const p=point(e);lastX=p.x;lastY=p.y});canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);x+=p.x-lastX;y+=p.y-lastY;lastX=p.x;lastY=p.y;draw()});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);
download.onclick=()=>{draw();canvas.toBlob(blob=>{const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='polaris-icon.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};
